spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/products/(?<segment>.*),/products/${segment}

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://user-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/users/(?<segment>.*),/users/${segment}

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=http://user-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/auth/(?<segment>.*),/auth/${segment}

jwt.secret=dGVzdHNlY3JldGtleXRlc3RzZWNyZXRrZXl0ZXN0c2VjcmV0a2V5dGVzdA==
jwt.expiration=86400000
jwt.refresh-expiration=604800000